[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
anyhow = "1"
duct = "1.0.0"
glob = "0.3.2"
fs_extra = "1.3.0"
dialoguer = "^0.11.0"