name: Detect Sensitive data
description: Report on detection sensitive data issue 
title: "[Detection summary]: "
labels: ["sensitive-data"]
body:
  - type: markdown
    attributes:
      value: |
        Do not add your sensitive data here!
  - type: textarea
    id: Suggestion
    attributes:
      label: Description
      description: Give more information about the sensitive data, such as app name/ example of the text that needs to catch 
      placeholder: Example here
      value: "Your sensitive pattern example" 
    validations:
      required: true
